apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/status
  - pods/portforward
  - namespaces
  - services
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - ""
  resourceNames: 
  - dev-namepsace
  resources: 
  - namespaces
  verbs: 
  - get
  - list
  - update
  - watch
  - create
  - update
  - delete
