apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-admin-bind
  namespace: dev-namespace
subjects:
- kind: ServiceAccount
  name: developer
  namespace: kube-system
roleRef:
  kind: Role
  name: developer-admin
  apiGroup: rbac.authorization.k8s.io

