apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
  namespace: your-namespace
data:
  allow-snippet-annotations: 'true'
  http-snippet: |
    limit_req_zone $binary_remote_addr_map zone=web_api:10m rate=300r/m;
    map $request_uri $binary_remote_addr_map {
      default "";
      ~^/foo/bar global;
    }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: your-ingress-name
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      limit_req zone=web_api;
      limit_req_status 429;
spec:
  rules:
    - host: your-hostname.com
      http:
        paths:
          - path: /your-path
            pathType: Prefix
            backend:
              service:
                name: your-service-name
                port:
                  number: your-service-port

